-- Helper for importing canonical CSV seed data under mixed FK policy.
-- Use with files in /data:
-- tblDonor.csv, tblBeneficiary.csv, tblProduct.csv, tblStorageZone.csv,
-- tblDonationLot.csv, tblInventory.csv, tblOrders.csv, tblOrderLine.csv,
-- tblPickAllocation.csv, tblZoneCapacityLog.csv

begin;

-- Allow explicit IDs from CSV import tools.
alter table public."tblDonor" alter column "DonorID" set generated by default;
alter table public."tblBeneficiary" alter column "BeneficiaryID" set generated by default;
alter table public."tblProduct" alter column "ProductID" set generated by default;
alter table public."tblStorageZone" alter column "ZoneID" set generated by default;
alter table public."tblDonationLot" alter column "LotID" set generated by default;
alter table public."tblInventory" alter column "InventoryID" set generated by default;
alter table public."tblOrders" alter column "OrderID" set generated by default;
alter table public."tblOrderLine" alter column "OrderLineID" set generated by default;
alter table public."tblPickAllocation" alter column "AllocationID" set generated by default;
alter table public."tblZoneCapacityLog" alter column "LogID" set generated by default;

-- Clean load to avoid duplicate PK errors.
truncate table
  public."tblPickAllocation",
  public."tblOrderLine",
  public."tblInventory",
  public."tblZoneCapacityLog",
  public."tblOrders",
  public."tblDonationLot",
  public."tblBeneficiary",
  public."tblDonor",
  public."tblProduct",
  public."tblStorageZone"
restart identity cascade;

commit;

-- Import in this order via Supabase Table Editor CSV import:
-- 1) tblDonor
-- 2) tblBeneficiary
-- 3) tblProduct
-- 4) tblStorageZone
-- 5) tblDonationLot
-- 6) tblInventory
-- 7) tblOrders
-- 8) tblOrderLine
-- 9) tblPickAllocation
-- 10) tblZoneCapacityLog

-- After import, sync identity sequences.
select setval(pg_get_serial_sequence('public."tblDonor"', 'DonorID'), coalesce(max("DonorID"), 1), true) from public."tblDonor";
select setval(pg_get_serial_sequence('public."tblBeneficiary"', 'BeneficiaryID'), coalesce(max("BeneficiaryID"), 1), true) from public."tblBeneficiary";
select setval(pg_get_serial_sequence('public."tblProduct"', 'ProductID'), coalesce(max("ProductID"), 1), true) from public."tblProduct";
select setval(pg_get_serial_sequence('public."tblStorageZone"', 'ZoneID'), coalesce(max("ZoneID"), 1), true) from public."tblStorageZone";
select setval(pg_get_serial_sequence('public."tblDonationLot"', 'LotID'), coalesce(max("LotID"), 1), true) from public."tblDonationLot";
select setval(pg_get_serial_sequence('public."tblInventory"', 'InventoryID'), coalesce(max("InventoryID"), 1), true) from public."tblInventory";
select setval(pg_get_serial_sequence('public."tblOrders"', 'OrderID'), coalesce(max("OrderID"), 1), true) from public."tblOrders";
select setval(pg_get_serial_sequence('public."tblOrderLine"', 'OrderLineID'), coalesce(max("OrderLineID"), 1), true) from public."tblOrderLine";
select setval(pg_get_serial_sequence('public."tblPickAllocation"', 'AllocationID'), coalesce(max("AllocationID"), 1), true) from public."tblPickAllocation";
select setval(pg_get_serial_sequence('public."tblZoneCapacityLog"', 'LogID'), coalesce(max("LogID"), 1), true) from public."tblZoneCapacityLog";

-- Optional: return identities to strict mode after import.
-- alter table public."tblDonor" alter column "DonorID" set generated always;
-- alter table public."tblBeneficiary" alter column "BeneficiaryID" set generated always;
-- alter table public."tblProduct" alter column "ProductID" set generated always;
-- alter table public."tblStorageZone" alter column "ZoneID" set generated always;
-- alter table public."tblDonationLot" alter column "LotID" set generated always;
-- alter table public."tblInventory" alter column "InventoryID" set generated always;
-- alter table public."tblOrders" alter column "OrderID" set generated always;
-- alter table public."tblOrderLine" alter column "OrderLineID" set generated always;
-- alter table public."tblPickAllocation" alter column "AllocationID" set generated always;
-- alter table public."tblZoneCapacityLog" alter column "LogID" set generated always;
